In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
path = kagglehub.dataset_download("masufaar/spotifycsv")

print("Path to dataset files:", path)

data = pd.read_csv(path + '/spotify.csv')
data.info()

/home/jonathan/Documents/GitHub/Kaggle_training/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /home/jonathan/.cache/kagglehub/datasets/masufaar/spotifycsv/versions/1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32833 entries, 0 to 32832
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   track_id                  32833 non-null  object
 1   track_name                32828 non-null  object
 2   track_artist              32828 non-null  object
 3   track_popularity          32833 non-null  int64
 4   track_album_id            32833 non-null  object
 5   track_album_name          32828 non-null  object
 6   track_album_release_date  32833 non-null  object
 7   playlist_name             32833 non-null  object
 8   playlist_id               32833 non-null  object
 9   playlist_genre            32833 non-null  object
 10  playlist_subgenre         32833 non-null  object
 11  danceability              32833 non-null  float64
 12  energy                    32833 non-null  float64
 13  key                       32833 non-null  int64
 14  loudness                  32833 non-null  float64
 15  mode                      32833 non-null  int64
 16  speechiness               32833 non-null  float64
 17  acousticness              32833 non-null  float64
 18  instrumentalness          32833 non-null  float64
 19  liveness                  32833 non-null  float64
 20  valence                   32833 non-null  float64
 21  tempo                     32833 non-null  float64
 22  duration_ms               32833 non-null  int64
dtypes: float64(9), int64(4), object(10)
memory usage: 5.8+ MB

In [2]:
data.columns

Index(['track_id', 'track_name', 'track_artist', 'track_popularity',
       'track_album_id', 'track_album_name', 'track_album_release_date',
       'playlist_name', 'playlist_id', 'playlist_genre', 'playlist_subgenre',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration_ms'],
      dtype='object')

In [3]:
import os
os.listdir('/home/jonathan/.cache/kagglehub/datasets/masufaar/spotifycsv/versions/1/')
#path+'/spotify.csv'

['spotify.csv']

In the kaggle instructions they say that they'll focus on the five popular songs from 2017 and 2018:

### Examine the data

The dataset for this tutorial tracks global daily streams on the music streaming service Spotify. We focus on five popular songs from 2017 and 2018:

1. "Shape of you", by Ed Sheeram
2. "Despacito", by Luis Fonzi
3. "Something just like this", by The Chainsmokers and Coldplay
4. "Humble", by Kendrick Lamar
5. "Unforgettable", by French Montana

Notice that the first date that appears is January 6, 2017, corresponding to the release date of "The Shape of You", by Ed Sheeran. And, using the table, you can see that "The Shape of You" was streamed 12,287,078 times globally on the day of its release. Notice that the other songs have missing values in the first row, because they weren't released until later!

In [47]:
# Seen the list of the columns from full dataset
data.columns

Index(['track_id', 'track_name', 'track_artist', 'track_popularity',
       'track_album_id', 'track_album_name', 'track_album_release_date',
       'playlist_name', 'playlist_id', 'playlist_genre', 'playlist_subgenre',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration_ms'],
      dtype='object')

In [48]:
# Here I created a list to make a filter with the selected artists and songs
artists = ['Ed Sheeran', 'Luis Fonsi', 'The Chainsmokers', 'Kendrick Lamar', 'French Montana']
songs = ['Shape of You', 'Despacito', 'Something Just Like This', 'HUMBLE.', 'Unforgettable']

In [ ]:
# The dataframe with the selected artists
df_selected_artist = data[data['track_artist'].isin(artists)]

In [50]:
# The dataframe with the selected songs
df_selected_songs = data[data['track_name'].isin(songs)]#['track_name'].value_counts()

In [71]:
# Preview of the dataframe with selected songs
df_selected_songs_ordered_by_date = df_selected_songs.sort_values(by='track_album_release_date').reset_index(drop=True)

In [ ]:
df_selected_songs_ordered_by_date

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,1F2HXIJrE2Xn81OzT2zZvW,Unforgettable,French Montana,14,1udLKdsDr7GRmJU6Cxyt7j,Unforgettable,2017,Indie Poptimism,2QiMewRbSavfZ9MSAYz2h6,pop,...,6,-5.043,1,0.1230,0.029300,0.010100,0.1040,0.733,97.985,233833
1,0FE9t6xYkqWXU2ahLh6D8X,Shape of You,Ed Sheeran,75,7oJa8bPFKVbq4c7NswXHw8,Shape of You,2017-01-06,Today's Hits (Clean),7ENISpOJhocpMJVcGb0qcT,r&b,...,1,-3.183,0,0.0802,0.581000,0.000000,0.0931,0.931,95.977,233713
2,0FE9t6xYkqWXU2ahLh6D8X,Shape of You,Ed Sheeran,75,7oJa8bPFKVbq4c7NswXHw8,Shape of You,2017-01-06,Tropical House Run 190 BPM,37i9dQZF1DWSTc9FdySHtz,latin,...,1,-3.183,0,0.0802,0.581000,0.000000,0.0931,0.931,95.977,233713
3,5AgTL2WmiCvoObA8fpncKs,Despacito,Luis Fonsi,58,3TZAHSlgnHCF5R4xNVgmOU,Shut Up Lets Dance,2017-02-17,School Dance 2019 (Squeaky Clean),0SqaMfNsngZCpPw0UuelA7,latin,...,2,-5.153,1,0.1130,0.216000,0.000000,0.1070,0.839,88.863,228200
4,1dNIEtp7AY3oDAKCGg2XkH,Something Just Like This,The Chainsmokers,76,7IzpJkWQqgz1BTutQvSitX,Something Just Like This,2017-02-22,Happy EDM,3d2JFEbvcx7p2CHkBaQeMZ,edm,...,11,-6.695,0,0.0362,0.030600,0.000025,0.1740,0.505,102.996,247627
5,1dNIEtp7AY3oDAKCGg2XkH,Something Just Like This,The Chainsmokers,76,7IzpJkWQqgz1BTutQvSitX,Something Just Like This,2017-02-22,Pop Inglés (2020 - 2010s)💙 Música En Inglés 2010s,4QAzO1Z92yqqD6Mf3mOANu,pop,...,11,-6.695,0,0.0362,0.030600,0.000025,0.1740,0.505,102.996,247627
6,1dNIEtp7AY3oDAKCGg2XkH,Something Just Like This,The Chainsmokers,76,7IzpJkWQqgz1BTutQvSitX,Something Just Like This,2017-02-22,Electropop Hits 2017-2020,7kyvBmlc1uSqsTL0EuNLrx,pop,...,11,-6.695,0,0.0362,0.030600,0.000025,0.1740,0.505,102.996,247627
7,7qiZfU4dY1lWllzX7mPBI3,Shape of You,Ed Sheeran,86,3T4tUhGYeRNVUGevb0wThu,÷ (Deluxe),2017-03-03,2010 - 2011 - 2012 - 2013 - 2014 - 2015 - 2016...,2DjIfVDXGYDgRxw7IJTKVb,edm,...,1,-3.183,0,0.0802,0.581000,0.000000,0.0931,0.931,95.977,233713
8,7qiZfU4dY1lWllzX7mPBI3,Shape of You,Ed Sheeran,86,3T4tUhGYeRNVUGevb0wThu,÷ (Deluxe),2017-03-03,Pop Inglés (2020 - 2010s)💙 Música En Inglés 2010s,4QAzO1Z92yqqD6Mf3mOANu,pop,...,1,-3.183,0,0.0802,0.581000,0.000000,0.0931,0.931,95.977,233713
9,7qiZfU4dY1lWllzX7mPBI3,Shape of You,Ed Sheeran,86,3T4tUhGYeRNVUGevb0wThu,÷ (Deluxe),2017-03-03,Today's Hits (Clean),7ENISpOJhocpMJVcGb0qcT,r&b,...,1,-3.183,0,0.0802,0.581000,0.000000,0.0931,0.931,95.977,233713
10,7qiZfU4dY1lWllzX7mPBI3,Shape of You,Ed Sheeran,86,3T4tUhGYeRNVUGevb0wThu,÷ (Deluxe),2017-03-03,post teen pop,6rjxP7GQKoqqgoakzxl3PY,pop,...,1,-3.183,0,0.0802,0.581000,0.000000,0.0931,0.931,95.977,233713
11,7qiZfU4dY1lWllzX7mPBI3,Shape of You,Ed Sheeran,86,3T4tUhGYeRNVUGevb0wThu,÷ (Deluxe),2017-03-03,ElectroPop 2020,4frhr6RQM2fMOm2mpvOVo6,pop,...,1,-3.183,0,0.0802,0.581000,0.000000,0.0931,0.931,95.977,233713
12,31c9IHwCIONmUYW0jL7Riz,HUMBLE.,Kendrick Lamar,7,745wm87LGZxRYeyGM0z96J,HUMBLE.,2017-03-31,"🔥💵 Hip Hop, Rap, Heavy 808's - New School",3jPkaExIWXQWklcmmF5180,rap,...,1,-7.507,0,0.1050,0.000359,0.000028,0.0897,0.418,149.992,177604
13,6RUKPb4LETWmmr3iAEQktW,Something Just Like This,The Chainsmokers,83,4JPguzRps3kuWDD5GS6oXr,Memories...Do Not Open,2017-04-07,Dance Pop,37i9dQZF1DWZQaaqNMbbXa,pop,...,11,-6.769,0,0.0317,0.049800,0.000014,0.1640,0.446,103.019,247160
14,6RUKPb4LETWmmr3iAEQktW,Something Just Like This,The Chainsmokers,83,4JPguzRps3kuWDD5GS6oXr,Memories...Do Not Open,2017-04-07,ElectroPop 2020,4frhr6RQM2fMOm2mpvOVo6,pop,...,11,-6.769,0,0.0317,0.049800,0.000014,0.1640,0.446,103.019,247160
15,7KXjTSCq5nL1LoYtL7XAwS,HUMBLE.,Kendrick Lamar,84,4eLPsYPBmXABThSJ821sqY,DAMN.,2017-04-14,Southern California Hip Hop Primer,206vi9Q0p3juAU73flxPsz,rap,...,1,-6.638,0,0.1020,0.000282,0.000054,0.0958,0.421,150.011,177000
16,7ujx3NYtwO2LkmKGz59mXp,HUMBLE.,Kendrick Lamar,12,7wbJhbCvhPfbK1CLAkpq25,DAMN.,2017-04-14,◤ Hip Hop Dance Music – Urban – Trap – Breakin...,0Hr2h94pKN8QAGVAgD6BsD,rap,...,1,-6.779,0,0.0903,0.000243,0.000032,0.0975,0.423,150.018,177000
17,7KXjTSCq5nL1LoYtL7XAwS,HUMBLE.,Kendrick Lamar,84,4eLPsYPBmXABThSJ821sqY,DAMN.,2017-04-14,10er Playlist,1kEczIkZH8IgaWT2BiApxZ,pop,...,1,-6.638,0,0.1020,0.000282,0.000054,0.0958,0.421,150.011,177000
18,7KXjTSCq5nL1LoYtL7XAwS,HUMBLE.,Kendrick Lamar,84,4eLPsYPBmXABThSJ821sqY,DAMN.,2017-04-14,Chixtape 5 - Tory Lanez,0UXwwVDipbBQeEX7h4YuKU,r&b,...,1,-6.638,0,0.1020,0.000282,0.000054,0.0958,0.421,150.011,177000
19,7KXjTSCq5nL1LoYtL7XAwS,HUMBLE.,Kendrick Lamar,84,4eLPsYPBmXABThSJ821sqY,DAMN.,2017-04-14,Hip pop,1Sc7bobknESH7SXQcnmoX5,r&b,...,1,-6.638,0,0.1020,0.000282,0.000054,0.0958,0.421,150.011,177000
20,7ujx3NYtwO2LkmKGz59mXp,HUMBLE.,Kendrick Lamar,12,7wbJhbCvhPfbK1CLAkpq25,DAMN.,2017-04-14,BALLARE - رقص,1CMvQ4Yr5DlYvYzI0Vc2UE,pop,...,1,-6.779,0,0.0903,0.000243,0.000032,0.0975,0.423,150.018,177000
21,7KXjTSCq5nL1LoYtL7XAwS,HUMBLE.,Kendrick Lamar,84,4eLPsYPBmXABThSJ821sqY,DAMN.,2017-04-14,Hip Hop Controller,37i9dQZF1DWT5MrZnPU1zD,rap,...,1,-6.638,0,0.1020,0.000282,0.000054,0.0958,0.421,150.011,177000
22,5ZiGdWZvv9kaWw1UFcmDur,Shape of You,EZA,2,5Zm0pvfZXgyVjo8uaCqcan,Shape of You,2017-05-19,Music&Other Drugs,5jROYSZSL7cO0jGAqkPx7C,pop,...,11,-9.708,0,0.2250,0.596000,0.000368,0.4870,0.652,176.000,225682
23,3B54sVLJ402zGa6Xm4YGNe,Unforgettable,French Montana,82,4c2p3TdN7NcQfCXyueCNnC,Jungle Rules,2017-07-14,10er Playlist,1kEczIkZH8IgaWT2BiApxZ,pop,...,6,-5.043,1,0.1230,0.029300,0.010100,0.1040,0.733,97.985,233902
24,6oZQUfZVGOwKmb9Zsjd0vx,Unforgettable,Aerreo,44,1N6bSsrepPdy2ZXbQ3iv3H,Unforgettable,2018-11-02,Pop Dance Hits,7eERKCkgNKCCx5GYdeMIZf,pop,...,0,-5.898,1,0.0248,0.093100,0.000037,0.2250,0.261,93.020,221935
25,6habFhsOp2NvshLv26DqMb,Despacito,Luis Fonsi,79,5C0YLr4OoRGFDaqdMQmkeH,VIDA,2019-02-01,2010 - 2011 - 2012 - 2013 - 2014 - 2015 - 2016...,2DjIfVDXGYDgRxw7IJTKVb,edm,...,2,-4.787,1,0.1530,0.198000,0.000000,0.0670,0.839,177.928,229360
26,6habFhsOp2NvshLv26DqMb,Despacito,Luis Fonsi,79,5C0YLr4OoRGFDaqdMQmkeH,VIDA,2019-02-01,Pop Latino 2019 - Mix Canciones Reggaeton & Po...,5ifDekrUt5lbSIMTSzNNqB,latin,...,2,-4.787,1,0.1530,0.198000,0.000000,0.0670,0.839,177.928,229360
27,6habFhsOp2NvshLv26DqMb,Despacito,Luis Fonsi,79,5C0YLr4OoRGFDaqdMQmkeH,VIDA,2019-02-01,Tusa - Karol G | China - Anuel AA | Estrenos R...,0T47pLnihK4xB8Bk9IQ0Dv,latin,...,2,-4.787,1,0.1530,0.198000,0.000000,0.0670,0.839,177.928,229360
28,6habFhsOp2NvshLv26DqMb,Despacito,Luis Fonsi,79,5C0YLr4OoRGFDaqdMQmkeH,VIDA,2019-02-01,post teen pop,6rjxP7GQKoqqgoakzxl3PY,pop,...,2,-4.787,1,0.1530,0.198000,0.000000,0.0670,0.839,177.928,229360

In [73]:
df_selected_songs_ordered_by_date.columns

Index(['track_id', 'track_name', 'track_artist', 'track_popularity',
       'track_album_id', 'track_album_name', 'track_album_release_date',
       'playlist_name', 'playlist_id', 'playlist_genre', 'playlist_subgenre',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration_ms'],
      dtype='object')

In [78]:
pd.crosstab(
    index= df_selected_songs_ordered_by_date['track_album_release_date'],
    columns=df_selected_songs_ordered_by_date['track_name'],
    values=df_selected_songs_ordered_by_date['loudness'],
    aggfunc='mean'
)

track_name,Despacito,HUMBLE.,Shape of You,Something Just Like This,Unforgettable
track_album_release_date,,,,,
2017,NaN,NaN,NaN,NaN,-5.043
2017-01-06,NaN,NaN,-3.183,NaN,NaN
2017-02-17,-5.153,NaN,NaN,NaN,NaN
2017-02-22,NaN,NaN,NaN,-6.695,NaN
2017-03-03,NaN,NaN,-3.183,NaN,NaN
2017-03-31,NaN,-7.507000,NaN,NaN,NaN
2017-04-07,NaN,NaN,NaN,-6.769,NaN
2017-04-14,NaN,-6.678286,NaN,NaN,NaN
2017-05-19,NaN,NaN,-9.708,NaN,NaN
2017-07-14,NaN,NaN,NaN,NaN,-5.043
2018-11-02,NaN,NaN,NaN,NaN,-5.898
2019-02-01,-4.787,NaN,NaN,NaN,NaN

In [54]:
data.query('track_name == "Despacito"')

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
2364,6habFhsOp2NvshLv26DqMb,Despacito,Luis Fonsi,79,5C0YLr4OoRGFDaqdMQmkeH,VIDA,2019-02-01,post teen pop,6rjxP7GQKoqqgoakzxl3PY,pop,...,2,-4.787,1,0.153,0.198,0.0,0.067,0.839,177.928,229360
18273,6habFhsOp2NvshLv26DqMb,Despacito,Luis Fonsi,79,5C0YLr4OoRGFDaqdMQmkeH,VIDA,2019-02-01,Pop Latino 2019 - Mix Canciones Reggaeton & Po...,5ifDekrUt5lbSIMTSzNNqB,latin,...,2,-4.787,1,0.153,0.198,0.0,0.067,0.839,177.928,229360
19205,6habFhsOp2NvshLv26DqMb,Despacito,Luis Fonsi,79,5C0YLr4OoRGFDaqdMQmkeH,VIDA,2019-02-01,Tusa - Karol G | China - Anuel AA | Estrenos R...,0T47pLnihK4xB8Bk9IQ0Dv,latin,...,2,-4.787,1,0.153,0.198,0.0,0.067,0.839,177.928,229360
21208,5AgTL2WmiCvoObA8fpncKs,Despacito,Luis Fonsi,58,3TZAHSlgnHCF5R4xNVgmOU,Shut Up Lets Dance,2017-02-17,School Dance 2019 (Squeaky Clean),0SqaMfNsngZCpPw0UuelA7,latin,...,2,-5.153,1,0.113,0.216,0.0,0.107,0.839,88.863,228200
30418,6habFhsOp2NvshLv26DqMb,Despacito,Luis Fonsi,79,5C0YLr4OoRGFDaqdMQmkeH,VIDA,2019-02-01,2010 - 2011 - 2012 - 2013 - 2014 - 2015 - 2016...,2DjIfVDXGYDgRxw7IJTKVb,edm,...,2,-4.787,1,0.153,0.198,0.0,0.067,0.839,177.928,229360

In [61]:
converted_dates = pd.to_datetime(data['track_album_release_date'], errors='coerce')
converted_dates.isna().sum()

np.int64(1886)

In [63]:
data[converted_dates.isna()]

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
151,2QtJA4gbwe1AcanB2p21aP,Stay The Night - Featuring Hayley Williams Of ...,Zedd,61,4xak0izXQHOMV9Wu1mDAAy,Clarity (Deluxe),2012,Dance Pop,37i9dQZF1DWZQaaqNMbbXa,pop,...,8,-3.109,1,0.0411,0.10900,0.000000,0.0947,0.461,127.961,217347
749,77j9HOrxUpWcjwra9jgvio,We like to Party! (Six Flags),Vengaboys,51,0R44mmTKUE1XCuGVVrPfTZ,We like to Party! (The Vengabus),1998,90s Dance Hits,50cXvxgMGrvoUeLhkzCyIO,pop,...,8,-7.929,1,0.0449,0.00803,0.859000,0.0460,0.969,136.018,224227
750,6rQ9qJPvInEqSzlh89LsPJ,Coco Jamboo - Radio Version,Mr. President,18,2t8Bc4qBseswbwOoHGHK8d,We See The Same Sun,1996,90s Dance Hits,50cXvxgMGrvoUeLhkzCyIO,pop,...,1,-5.414,0,0.0421,0.07910,0.000000,0.1520,0.965,100.019,218733
751,5FgtdSf7I5lClThz2ptWvl,Blue (Da Ba Dee),Eiffel 65,16,65DySolRDG1LNSvRXcWQWN,Europop,1999,90s Dance Hits,50cXvxgMGrvoUeLhkzCyIO,pop,...,7,-11.471,0,0.0582,0.25900,0.000162,0.3900,0.765,128.007,283748
753,2ahnofp2LbBWDXcJbMaSTu,What Is Love,Haddaway,70,0qTVjeVP70YvQG4GctetOf,What is Love - Remix,1993,90s Dance Hits,50cXvxgMGrvoUeLhkzCyIO,pop,...,7,-7.907,0,0.0311,0.02220,0.014900,0.2030,0.737,123.871,270373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32360,0363w3IUcO4cJMsAFLpfLY,Faith - Radio Edit,Blasterjaxx,0,1IZUFYTXNbjkzgawT7cFpM,Faith,2013,Gym (Melbourne Bounce/Progressive House),5BqOZpVEqRDfZScvW1QUyA,edm,...,9,-6.566,0,0.0486,0.00636,0.002310,0.1870,0.670,128.009,183067
32767,1h7LBCgfnSUEe7qXRbwMIp,Push Play,Zedd,39,4xak0izXQHOMV9Wu1mDAAy,Clarity (Deluxe),2012,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,9,-1.440,1,0.0459,0.08680,0.000000,0.0841,0.252,130.030,219360
32774,1NtVWYw9QDr30Ei0phACni,Lessons In Love (feat. Neon Trees),Kaskade,23,7r47EiktL01BmvI7NHdgcA,Fire & Ice,2011,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,7,-4.335,1,0.0540,0.02650,0.000013,0.1330,0.597,127.989,247693
32775,454ZIylnCq09ONjQE4EJ6a,Turn It Down (with Rebecca & Fiona) - Radio Edit,Kaskade,13,0xiigD6kCGMSv9CcSpJFUr,"I Love You, Man (Bonus Track Version)",2011,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,5,-7.922,0,0.0455,0.05360,0.008350,0.3390,0.413,126.971,238360
32827,0aBDrRTgDCwWbcOnEIp7DJ,Many Ways - Radio Edit,Ferry Corsten feat. Jenny Wahlstrom,27,59XOfNjuYZB6feC6QUzS3e,Many Ways,2013,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,5,-8.367,1,0.0365,0.02660,0.000000,0.5720,0.288,128.001,196993

In [66]:
converted_dates[converted_dates.isna()]

151     NaT
749     NaT
750     NaT
751     NaT
753     NaT
         ..
32360   NaT
32767   NaT
32774   NaT
32775   NaT
32827   NaT
Name: track_album_release_date, Length: 1886, dtype: datetime64[ns]

In [79]:
data

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,6f807x0ima9a1j3VPbc7VN,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,6,-2.634,1,0.0583,0.102000,0.000000,0.0653,0.5180,122.036,194754
1,0r7CVbZTWZgbTCYdfa2P31,Memories - Dillon Francis Remix,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,11,-4.969,1,0.0373,0.072400,0.004210,0.3570,0.6930,99.972,162600
2,1z1Hg7Vb0AhHDiEmnDE79l,All the Time - Don Diablo Remix,Zara Larsson,70,1HoSmj2eLcsrR0vE9gThr4,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-3.432,0,0.0742,0.079400,0.000023,0.1100,0.6130,124.008,176616
3,75FpbthrwQmzHlBJLuGdC7,Call You Mine - Keanu Silva Remix,The Chainsmokers,60,1nqYsOef1yKKuGOVchbsk6,Call You Mine - The Remixes,2019-07-19,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,7,-3.778,1,0.1020,0.028700,0.000009,0.2040,0.2770,121.956,169093
4,1e8PAfcKUYoKkxPhrHqw4x,Someone You Loved - Future Humans Remix,Lewis Capaldi,69,7m7vv9wlQ4i0LFuJiE2zsQ,Someone You Loved (Future Humans Remix),2019-03-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-4.672,1,0.0359,0.080300,0.000000,0.0833,0.7250,123.976,189052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32828,7bxnKAamR3snQ1VGLuVfC1,City Of Lights - Official Radio Edit,Lush & Simon,42,2azRoBBWEEEYhqV6sb7JrT,City Of Lights (Vocal Mix),2014-04-28,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,2,-1.814,1,0.0936,0.076600,0.000000,0.0668,0.2100,128.170,204375
32829,5Aevni09Em4575077nkWHz,Closer - Sultan & Ned Shepard Remix,Tegan and Sara,20,6kD6KLxj7s8eCE3ABvAyf5,Closer Remixed,2013-03-08,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,0,-4.462,1,0.0420,0.001710,0.004270,0.3750,0.4000,128.041,353120
32830,7ImMqPP3Q1yfUHvsdn7wEo,Sweet Surrender - Radio Edit,Starkillers,14,0ltWNSY9JgxoIZO4VzuCa6,Sweet Surrender (Radio Edit),2014-04-21,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,6,-4.899,0,0.0481,0.108000,0.000001,0.1500,0.4360,127.989,210112
32831,2m69mhnfQ1Oq6lGtXuYhgX,Only For You - Maor Levi Remix,Mat Zo,15,1fGrOkHnHJcStl14zNx8Jy,Only For You (Remixes),2014-01-01,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,2,-3.361,1,0.1090,0.007920,0.127000,0.3430,0.3080,128.008,367432
32832,29zWqhca3zt5NsckZqDf6c,Typhoon - Original Mix,Julian Calor,27,0X3mUOm6MhxR7PzxG95rAo,Typhoon/Storm,2014-03-03,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,5,-4.571,0,0.0385,0.000133,0.341000,0.7420,0.0894,127.984,337500